# Generated by Django 2.1.7 on 2019-08-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroom',
            name='para1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='para10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='para2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='para3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='para4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='para5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='para6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='para7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='para8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='para9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='photo10',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='photo6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='photo7',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='photo8',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='newsroom',
            name='photo9',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
