# Generated by Django 3.2.6 on 2021-12-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190813_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
